management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/sample?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
