scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:8080']
  - job_name: 'counter metric'
    metrics_path: '/query/label'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:8080']
  - job_name: 'gauge metric'
    metrics_path: '/query/gauge'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:8080']
